config/routes.rb
Login::Application.routes.draw do
  resources :users, only: [:index, :show, :new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase!}

    has_secure_password

    def self.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def self.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            sign_in user
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        sign_out
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user, only: [:edit, :update]
    before_action :correct_user, only: [:edit, :update]

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def edit
    end

    def create
        @user = User.new(user_params)
        if @user.save
            sign_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def update
        if @user.update_attributes(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end

        def correct_user
            @user = User.find(params[:id])
            redirect_to root_url unless current_user?(@user)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        remember_token = User.new_remember_token
        cookies.permanent[:remember_token] = remember_token
        user.update_attribute(:remember_token, User.encrypt(remember_token))
        self.current_user = user
    end

    def sign_out
        self.current_user = nil
        cookies.delete(:remember_token)
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
        remember_token = User.encrypt(cookies[:remember_token])
        @current_user ||=User.find_by(remember_token: remember_token)
    end

    def current_user?(user)
        user == current_user
    end
        
    def signed_in?
        !current_user.nil?
    end

    def signed_in_user
        redirect_to signin_url unless signed_in?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

<ul>
<li><%= link_to 'ユーザ一覧', users_path %></li>
<% if signed_in?%>
<li><%= link_to 'プロフィール', current_user %></li>
<li><%= link_to 'ログアウト', signout_path, method: :delete %></li>
<% else %>
<li><%= link_to 'ログイン', signin_path%></li>
<li><%= link_to 'アカウント作成', signup_path%></li>
<% end %>
</ul>

<hr>

    <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<h1>アカウント編集</h1>

<%= form_for(@user) do |f| %>
    <table border="1">
        <tr>
            <th><%= f.label :name, '名前' %></th>
            <td><%= f.text_field :name %></td>
        </tr>
        <tr>
            <th><%= f.label :email, 'メールアドレス' %></th>
            <td><%= f.text_field :email %></td>
        </tr>
        <tr>
            <th><%= f.label :password, 'パスワード'%></th>
            <td><%= f.password_field :password %></td>
        </tr>
        <tr>
            <th><%= f.label :password_confirmation, '確認' %></th>
            <td><%= f.password_field :password_confirmation %></td>
        </tr>
    </table>

<%= f.submit 'アカウントを編集する' %>

<% end %>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>

<ul>
    <% @users.each do |user| %>
    <li><%= link_to user.name, user %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>アカウント作成</h1>

<%= form_for(@user) do |f| %>

    <table border="1">
        <tr>
            <th><%= f.label :name, '名前' %></th>
            <td><%= f.text_field :name %></td>
        </tr>
        <tr>
            <th><%= f.label :email, 'メールアドレス' %></th>
            <td><%= f.text_field :email %></td>
        </tr>
        <tr>
            <th><%= f.label :password, 'パスワード '%></th>
            <td><%= f.password_field :password %></td>
        </tr>
        <tr>
            <th><%= f.label :password_confirmation, '確認' %></th>
            <td><%= f.password_field :password_confirmation %></td>
        </tr>
    </table>
    <%= f.submit 'アカウントを作成する' %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザ情報</h1>

<table border="1">
    <tr>
        <th>名前</th>
        <td><%= @user.name %></td>
    </tr>
    <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
    </tr>
</table>

<% if current_user?(@user) %>
<p><%= link_to '編集', edit_user_path %></p>
<% end %>